var text = {
    "info": {
        "id": "sb/8/6/summary",
        "prevId": "sb/8/5/50",
        "nextId": "sb/8/6/1"
    },
    "verses": null,
    "synonyms": null,
    "translation": null,
    "purport": [
        {
            "type": "normal",
            "content": "This chapter describes how the Lord appeared before the demigods when they offered Him their prayers. Following the advice of the Supreme Personality of Godhead, the demigods executed a truce with the demons for the purpose of churning nectar from the sea."
        },
        {
            "type": "normal",
            "content": "Because of the prayers offered by the demigods in the previous chapter, Lord Kñérodakaçäyé Viñëu was pleased with the demigods, and thus He appeared before them. The demigods were almost blinded by His transcendental bodily effulgence. At first, therefore, they could not even see any part of His body. After some time, however, when Brahmä could see the Lord, he, along with Lord Çiva, began to offer the Lord prayers."
        },
        {
            "type": "normal",
            "content": "Lord Brahmä said: \"The Supreme Personality of Godhead, being beyond birth and death, is eternal. He has no material qualities. Yet He is the ocean of unlimited auspicious qualities. He is subtler than the most subtle, He is invisible, and His form is inconceivable. He is worshipable for all the demigods. Innumerable universes exist within His form, and therefore He is never separated from these universes by time, space or circumstances. He is the chief and the pradhäna. Although He is the beginning, the middle and the end of the material creation, the idea of pantheism conceived by Mäyävädé philosophers has no validity. The Supreme Personality of Godhead controls the entire material manifestation through His subordinate agent, the external energy. Because of His inconceivable transcendental position, He is always the master of the material energy. The Supreme Personality of Godhead, in His various forms, is always present even within this material world, but the material qualities cannot touch Him. One can understand His position only by His instructions, as given in Bhagavad-gétä.\" As stated in Bhagavad-gétä , dadämi buddhi-yogaà tam. Buddhi-yoga means bhakti-yoga. Only through the process of bhakti-yoga can one understand the Supreme Lord."
        },
        {
            "type": "normal",
            "content": "When offered prayers by Lord Çiva and Lord Brahmä, the Supreme Personality of Godhead was pleased. Thus He gave appropriate instructions to all the demigods. The Supreme Personality of Godhead, who is known as Ajita, unconquerable, advised the demigods to make a peace proposal to the demons, so that after formulating a truce, the demigods and demons could churn the ocean of milk. The rope would be the biggest serpent, known as Väsuki, and the churning rod would be Mandara Mountain. Poison would also be produced from the churning, but it would be taken by Lord Çiva, and so there would be no need to fear it. Many other attractive things would be generated by the churning, but the Lord warned the demigods not to be captivated by such things. Nor should the demigods be angry if there were some disturbances. After advising the demigods in this way, the Lord disappeared from the scene."
        },
        {
            "type": "normal",
            "content": "Following the instructions of the Supreme Personality of Godhead, the demigods established a peace with Mahäräja Bali, the King of the demons. Then both the demons and the demigods started for the ocean, taking Mandara Mountain with them. Because of the great heaviness of the mountain, the demigods and demons became fatigued, and some of them actually died. Then the Supreme Personality of Godhead, Viñëu, appeared there on the back of His carrier, Garuòa, and by His mercy He brought these demigods and demons back to life. The Lord then lifted the mountain with one of His hands and placed it on the back of Garuòa. The Lord sat on the mountain and was carried to the spot of the churning by Garuòa, who placed the mountain in the middle of the sea. Then the Lord asked Garuòa to leave that place because as long as Garuòa was present, Väsuki could not come there."
        }
    ]
}

