var text = {
    "info": {
        "id": "sb/8/7/summary",
        "prevId": "sb/8/6/39",
        "nextId": "sb/8/7/1"
    },
    "verses": null,
    "synonyms": null,
    "translation": null,
    "purport": [
        {
            "type": "normal",
            "content": "The summary of the Seventh Chapter is as follows. As described in this chapter, the Supreme Personality of Godhead, appearing in His incarnation as a tortoise, dove deep into the ocean to carry Mandara Mountain on His back. At first the churning of the ocean produced kälaküöa poison. Everyone feared this poison, but Lord Çiva satisfied them by drinking it."
        },
        {
            "type": "normal",
            "content": "With the understanding that when the nectar was generated from the churning they would share it equally, the demigods and the demons brought Väsuki to be used as the rope for the churning rod. By the expert arrangement of the Supreme Personality of Godhead, the demons held the snake near the mouth, whereas the demigods held the tail of the great snake. Then, with great endeavor, they began pulling the snake in both directions. Because the churning rod, Mandara Mountain, was very heavy and was not held by any support in the water, it sank into the ocean, and in this way the prowess of both the demons and the demigods was vanquished. The Supreme Personality of Godhead then appeared in the form of a tortoise and supported Mandara Mountain on His back. Then the churning resumed with great force. As a result of the churning, a huge amount of poison was produced. The prajäpatis, seeing no one else to save them, approached Lord Çiva and offered him prayers full of truth. Lord Çiva is called Äçutoña because he is very pleased if one is a devotee. Therefore he easily agreed to drink all the poison generated by the churning. The goddess Durgä, Bhaväné, the wife of Lord Çiva, was not at all disturbed when Lord Çiva agreed to drink the poison, for she knew Lord Çiva's prowess. Indeed, she expressed her pleasure at this agreement. Then Lord Çiva gathered the devastating poison, which was everywhere. He took it in his hand and drank it. After he drank the poison, his neck became bluish. A small quantity of the poison dropped from his hands to the ground, and it is because of this poison that there are poisonous snakes, scorpions, toxic plants and other poisonous things in this world."
        }
    ]
}

